### ISSUE TITLE
more complete checks required on predict REST call

### ISSUE THREAD

**Issue by lmamakos** [robmarkcole/HASS-Google-Coral#4]
Right now, the code in the custom component checks for HTTP_OK status (200) before referencing "predictions" in the JSON response.  Under some circumstances, a JSON response of

```json
{"success":false}
```

is returned instead.  Typically, if you send a bogus image format in the POST.  You can see this by doing a `curl  -v -X POST -F image=""  localhost:5000/predict` command.

I noticed this failing on my Home Assistant installation on a subset of cameras that I have that are MJPEG (motion JPEG) cameras.  Apparently there's a problem requesting them to grab an image frame on demand.  I can see this by calling the `camera.snapshot` service on one of those cameras and not having a file created.  That particular bug is out of scope for this issue, we should just be more diligent and check a bit more closely to avoid filling up the log with errors like:
```
2019-06-16 01:10:19 ERROR (MainThread) [homeassistant.helpers.entity] Update for image_processing.cam4_coral fails
Traceback (most recent call last):
  File "/usr/src/app/homeassistant/helpers/entity.py", line 220, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/app/homeassistant/helpers/entity.py", line 375, in async_device_update
    await self.async_update()
  File "/usr/src/app/homeassistant/components/image_processing/__init__.py", line 132, in async_update
    await self.async_process_image(image.content)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/google_coral/image_processing.py", line 117, in process_image
    predictions_json = response.json()["predictions"]
KeyError: 'predictions'
```
every few seconds.  

I think the code that actually tries to grab the image is in a superclass of the component itself..

**Comment by lmamakos** [comment]
Maybe something crude like

```
--- image_processing.py.original	2019-06-16 01:16:12.814584259 -0400
+++ image_processing.py	2019-06-16 01:25:15.446569401 -0400
@@ -112,17 +112,18 @@
         """Process an image."""
         response = post_image(
             self._url_predict, image)
+
+        self._state = None
+        self._predictions = {}
         if response:
             if response.status_code == HTTP_OK:
-                predictions_json = response.json()["predictions"]
-                self._state = get_object_instances(
-                    predictions_json, self._target, self._confidence)
-                self._predictions = get_objects_summary(
-                    predictions_json, self._confidence)
-
-        else:
-            self._state = None
-            self._predictions = {}
+                response_json  = response.json()
+                if response_json["success"]:
+                    predictions_json = response_json["predictions"]
+                    self._state = get_object_instances(
+                        predictions_json, self._target, self._confidence)
+                    self._predictions = get_objects_summary(
+                        predictions_json, self._confidence)

     @property
     def camera_entity(self):
```
which I need to test a bit more throughly, but you probably get the idea.  I'm not sure this is directly applicable if you're enhancing the component to store annotated images.
